export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const ADD_INGREDIENT_BUN = 'ADD_INGREDIENT_BUN';
export const ADD_INGREDIENT_BUN_LAST = 'ADD_INGREDIENT_BUN_LAST';

export const DELETE_INGREDIENT = 'DELETE_INGREDIENT';
export const DELETE_DETAILS = 'DELETE_DETAILS';