export const CHANGE_INGREDIENT = 'CHANGE_INGREDIENT';
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const DELETE_INGREDIENT = 'DELETE_INGREDIENT';
export const DELETE_DETAILS = 'DELETE_DETAILS';