export const LOAD_INGREDIENTS = 'LOAD_INGREDIENTS';
export const LOAD_CONSTRUCTOR = 'LOAD_CONSTRUCTOR';
export const LOAD_DETAILS = 'LOAD_DETAILS';

export const LOAD_INGREDIENTS_REQIEST = 'LOAD_INGREDIENTS_REQIEST';
export const LOAD_INGREDIENTS_SUCCESS = 'LOAD_INGREDIENTS_SUCCESS';
export const LOAD_INGREDIENTS_FAILED = 'LOAD_INGREDIENTS_FAILED';

